[package]
name = "serde_sqlite"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.3.4"

[dev-dependencies]
rusqlite = "0.21.0"
tempfile = "3.1.0"
rand = "0.7.3"
